
Start cleaning abstracts of level_2 articles

[Wed Apr  3 17:36:11 2024]   1000 abstracts inserted in 54.4 sec, overall it's 18.4 abstracts/sec
[Wed Apr  3 17:37:25 2024]   1000 abstracts inserted in 73.6 sec, overall it's 13.6 abstracts/sec
[Wed Apr  3 17:38:34 2024]   1000 abstracts inserted in 69.2 sec, overall it's 14.5 abstracts/sec
[Wed Apr  3 17:39:38 2024]   1000 abstracts inserted in 64.1 sec, overall it's 15.6 abstracts/sec
[Wed Apr  3 17:41:04 2024]   1000 abstracts inserted in 85.6 sec, overall it's 11.7 abstracts/sec
[Wed Apr  3 17:42:19 2024]   1000 abstracts inserted in 74.7 sec, overall it's 13.4 abstracts/sec
[Wed Apr  3 17:42:57 2024]   Something wrong with cleaning {}. Error
:Traceback (most recent call last):
  File "c:\users\asus\onedrive\документы\github\articles-analysis\programs\text_preprocessing.py", line 92, in clean_single_abstract
    return reproc(abstract)
  File "cytoolz\\functoolz.pyx", line 518, in cytoolz.functoolz.Compose.__call__
  File "C:\Users\Asus\OneDrive\Документы\GitHub\articles-analysis\programs\helpfun.py", line 226, in inv_index_by_abstract
    if text[0] == '[':
IndexError: string index out of range


[Wed Apr  3 17:43:37 2024]   999 abstracts inserted in 78.4 sec, overall it's 12.7 abstracts/sec
[Wed Apr  3 17:43:39 2024]   Something wrong with cleaning {}. Error
:Traceback (most recent call last):
  File "c:\users\asus\onedrive\документы\github\articles-analysis\programs\text_preprocessing.py", line 92, in clean_single_abstract
    return reproc(abstract)
  File "cytoolz\\functoolz.pyx", line 518, in cytoolz.functoolz.Compose.__call__
  File "C:\Users\Asus\OneDrive\Документы\GitHub\articles-analysis\programs\helpfun.py", line 226, in inv_index_by_abstract
    if text[0] == '[':
IndexError: string index out of range


[Wed Apr  3 17:44:39 2024]   999 abstracts inserted in 62.4 sec, overall it's 16.0 abstracts/sec
[Wed Apr  3 17:44:41 2024]   Something wrong with cleaning {}. Error
:Traceback (most recent call last):
  File "c:\users\asus\onedrive\документы\github\articles-analysis\programs\text_preprocessing.py", line 92, in clean_single_abstract
    return reproc(abstract)
  File "cytoolz\\functoolz.pyx", line 518, in cytoolz.functoolz.Compose.__call__
  File "C:\Users\Asus\OneDrive\Документы\GitHub\articles-analysis\programs\helpfun.py", line 226, in inv_index_by_abstract
    if text[0] == '[':
IndexError: string index out of range


[Wed Apr  3 17:45:46 2024]   999 abstracts inserted in 66.4 sec, overall it's 15.0 abstracts/sec
[Wed Apr  3 17:45:49 2024]   Something wrong with cleaning {}. Error
:Traceback (most recent call last):
  File "c:\users\asus\onedrive\документы\github\articles-analysis\programs\text_preprocessing.py", line 92, in clean_single_abstract
    return reproc(abstract)
  File "cytoolz\\functoolz.pyx", line 518, in cytoolz.functoolz.Compose.__call__
  File "C:\Users\Asus\OneDrive\Документы\GitHub\articles-analysis\programs\helpfun.py", line 226, in inv_index_by_abstract
    if text[0] == '[':
IndexError: string index out of range


[Wed Apr  3 17:47:20 2024]   999 abstracts inserted in 94.0 sec, overall it's 10.6 abstracts/sec
[Wed Apr  3 17:47:23 2024]   Something wrong with cleaning {}. Error
:Traceback (most recent call last):
  File "c:\users\asus\onedrive\документы\github\articles-analysis\programs\text_preprocessing.py", line 92, in clean_single_abstract
    return reproc(abstract)
  File "cytoolz\\functoolz.pyx", line 518, in cytoolz.functoolz.Compose.__call__
  File "C:\Users\Asus\OneDrive\Документы\GitHub\articles-analysis\programs\helpfun.py", line 226, in inv_index_by_abstract
    if len(text) == 0:
IndexError: string index out of range


[Wed Apr  3 17:48:49 2024]   999 abstracts inserted in 88.8 sec, overall it's 11.2 abstracts/sec
[Wed Apr  3 17:48:49 2024]   Something wrong with cleaning {}. Error
:Traceback (most recent call last):
  File "c:\users\asus\onedrive\документы\github\articles-analysis\programs\text_preprocessing.py", line 92, in clean_single_abstract
    return reproc(abstract)
  File "cytoolz\\functoolz.pyx", line 518, in cytoolz.functoolz.Compose.__call__
  File "C:\Users\Asus\OneDrive\Документы\GitHub\articles-analysis\programs\helpfun.py", line 226, in inv_index_by_abstract
    if len(text) == 0:
IndexError: string index out of range


[Wed Apr  3 17:49:25 2024]   Something wrong with cleaning {}. Error
:Traceback (most recent call last):
  File "c:\users\asus\onedrive\документы\github\articles-analysis\programs\text_preprocessing.py", line 92, in clean_single_abstract
    return reproc(abstract)
  File "cytoolz\\functoolz.pyx", line 518, in cytoolz.functoolz.Compose.__call__
  File "C:\Users\Asus\OneDrive\Документы\GitHub\articles-analysis\programs\helpfun.py", line 226, in inv_index_by_abstract
    if len(text) == 0:
IndexError: string index out of range


